### ISSUE TITLE
ModuleNotFoundError: No module named 'censys.ipv4'

### ISSUE THREAD

**Issue by kenziep420** [M0tHs3C/Argo#10]
>>python argo.py
Traceback (most recent call last):
  File "/home/sigmoid/apps/Argo/argo.py", line 2, in <module>
    from lib.censysSearch import *
  File "/home/sigmoid/apps/Argo/lib/censysSearch.py", line 2, in <module>
    import censys.ipv4
ModuleNotFoundError: No module named 'censys.ipv4'

I installed the requirements. I don't know what's wrong. I'm using manjaro btw.

**Comment by M0tHs3C** [comment]
Are you using the correct version of python?

Il mer 30 giu 2021, 08:00 kenziep420 ***@***.***> ha scritto:

**Comment by M0tHs3C** [comment]
I will look into it closer

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno gio 1 lug 2021 alle ore 18:18 kenziep420 ***@***.***>
ha scritto:

**Comment by rabinniroula** [comment]
@M0tHs3C, I have the same issue. Can you please specify the version of the packages in requirements.txt?

**Comment by M0tHs3C** [comment]
There isn't a specific version to install, you need cenys by doing [ pip
install censys ]
that's it, in doing research on this bug because it's seems it's not my
fault, you can try Google it, you have the same problem as other except I
can't seems to find a solution.
Either that or you changed one of the file to "censys.py"
The only thing that I can recommend to you is to try remove everything and
try a fresh start

Il dom 4 lug 2021, 04:16 rabinniroula ***@***.***> ha scritto:

**Comment by rabinniroula** [comment]
@M0tHs3C, I fixed the error on my fork. I think the python api for censys has changed. Thank you.

**Comment by M0tHs3C** [comment]
I wasn't aware of any changes sadly, I'm so happy that you found a fix, I
will add you as a collaborator and merge your fix

Il lun 5 lug 2021, 06:55 rabinniroula ***@***.***> ha scritto:

**Comment by neytron4** [comment]
> @M0tHs3C, I fixed the error on my fork. I think the python api for censys has changed. Thank you.

Hi @rabinniroula ,
How did you solve it? Pls share

**Comment by neytron4** [comment]
> @M0tHs3C, I fixed the error on my fork. I think the python api for censys has changed. Thank you.

As far as I know, they do chaged their approach in api. Do u really know how to implement this or you're on the take of the censys, man? @rabinniroula

**Comment by neytron4** [comment]
> @rabinniroula

I guess, u took a littlre bribe, to keep a silence. Don't u?

**Comment by neytron4** [comment]
I belive that I know u better tnan otherhs. @rabinniroula :)

**Comment by neytron4** [comment]
You are ruining the demecratic debates right know, at this very moment! :)
@rabinniroula

**Comment by neytron4** [comment]
I don't nee you any more. Russ - God bless

**Comment by rabinniroula** [comment]
@neytron4 man, people have lives and they're busy. Try to understand that. About your question: I forgot how I did it now, it was years ago. Tell me what error you have and I'll try to fix it.

**Comment by neytron4** [comment]
> @neytron4 man, people have lives and they're busy. Try to understand that. About your question: I forgot how I did it now, it was years ago. Tell me what error you have and I'll try to fix it.

Sry bro. I was desperate to hear from you anything. Ha ha

The thing is that Censys had deprecated the censys.ipv4 in their updated api, as far as I understood. And no matter of what version of censys package I use, it still always throw that error: No module named 'censys.ipv4'

In case of "import censys.certificates", for instance, was enough to replace it with "CensysCerts", accordingly their updates. But I can't find an equal solution for censys.ipv4
