### ISSUE TITLE
Gather more than 100 results

### ISSUE THREAD

**Issue by pispuso** [M0tHs3C/Argo#14]
Hello!

First of all, thanks for this amazing tool!

Is there a way to gather more than 100 results when searching in Shodan or is an API limitation that I'm not aware of?

Thanks in advance!

**Comment by M0tHs3C** [comment]
it's an API limitation made by shodan, I'm afraid that the only solution to
this is just to pay the license.

Il mer 10 nov 2021, 19:45 pispuso ***@***.***> ha scritto:
