### ISSUE TITLE
Country Search

### ISSUE THREAD

**Issue by rjack640** [M0tHs3C/Argo#17]
Is there a way to search by country with shodan? I tried to edit queryBuilder.py like this "query = 'http.favicon.hash:999357577 country: DE'" but i didn't work.

**Comment by M0tHs3C** [comment]
Hi,
This tool is built around the free version of the API, both shodan and
censys.
unfortunately shodan doesn't allow you to query a specific country with the
free plan.
I'm closing this issue
best regards

Il sab 15 gen 2022, 15:01 rjack640 ***@***.***> ha scritto:

**Comment by M0tHs3C** [comment]
closing
