### ISSUE TITLE
problems with line2

### ISSUE THREAD

**Issue by kkk-alt** [M0tHs3C/Argo#2]
traceback (most recent call last):
  File "argo.py", line 2, in <module>
    from lib.censysSearch import *
ImportError: No module named lib.censysSearch

**Comment by kkk-alt** [comment]
Problems in Parrot last version  using URLLIB
Requirement already satisfied: urllib3 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 4)) (1.24.1)
Collecting urllib (from -r requirements.txt (line 5))
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/urllib/

**Comment by M0tHs3C** [comment]
There is a problem with your operating system
Then
You are trying to use python2.7
This works with python3
Read the readme before opening a issue

**Comment by KassNT** [comment]
> traceback (most recent call last): File "argo.py", line 2, in from lib.censysSearch import * ImportError: No module named lib.censysSearch

This is my problem too...  using python3
