### ISSUE TITLE
Custom Query Syntax

### ISSUE THREAD

**Issue by Dom-Sathanas** [M0tHs3C/Argo#6]
Hi there, can you tell me the proper syntax for a custom query against a specific IP for a Hikvision camera. When I enter an IP address after selecting the custom query option, i just get sent back to the menu. Thanks.

**Comment by M0tHs3C** [comment]
the query for the hikvision camera is already stored, you dont have to do a custom query.
The custom query is a query, not a search bar
you have no reason to put an IP address in a query builder
